fixtures:
  repositories:
    'stdlib':
      repo: 'git://github.com/puppetlabs/puppetlabs-stdlib.git'
      ref: '4.6.0'
    'epel':
      repo: 'git://github.com/stahnma/puppet-module-epel.git'
      ref: '1.2.2'
  symlinks:
    python: "#{source_dir}"
