name          'stankevich-python'
version       '1.7.8'
source        'git://github.com/stankevich/puppet-python.git'
author        'Sergey Stankevich'
license       'Apache 2.0'
summary       'Python Module'
description   'Puppet module for Python'
project_page  'https://github.com/stankevich/puppet-python'
dependency    'puppetlabs/stdlib', '>= 4.3.2'
